/**
 * MdNotesCCGLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { ServiceStatus, serviceStatusSchema } from '../models/serviceStatus';
import { BaseController } from './baseController';

export class ServiceController extends BaseController {
  /**
   * @return Response from the API call
   */
  async getStatus(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ServiceStatus>> {
    const req = this.createRequest('GET', '/status');
    req.authenticate([{ httpCCG: true }]);
    return req.callAsJson(serviceStatusSchema, requestOptions);
  }
}
