/**
 * MdNotesCCGLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { User, userSchema } from '../models/user';
import { BaseController } from './baseController';

export class UserController extends BaseController {
  /**
   * @return Response from the API call
   */
  async getUser(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<User>> {
    const req = this.createRequest('GET', '/user');
    req.authenticate([{ httpCCG: true }]);
    return req.callAsJson(userSchema, requestOptions);
  }
}
