/**
 * MdNotesCCGLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { expandoObject, number, optional, Schema, string } from '../schema';

export interface ServiceStatus {
  app?: string;
  moto?: string;
  notes?: number;
  users?: number;
  time?: string;
  os?: string;
  phpVersion?: string;
  status: string;
  [key: string]: unknown;
}

export const serviceStatusSchema: Schema<ServiceStatus> = expandoObject({
  app: ['app', optional(string())],
  moto: ['moto', optional(string())],
  notes: ['notes', optional(number())],
  users: ['users', optional(number())],
  time: ['time', optional(string())],
  os: ['os', optional(string())],
  phpVersion: ['php_version', optional(string())],
  status: ['status', string()],
});
